bulletin_board/urls.py
from django.urls import path
from .views import bboard_index, contacts, by_rubric, BbCreateView, see_user_info

app_name = 'bboard'

urlpatterns = [
    path('', bboard_index, name='index'),
    path('hi/', see_user_info, name='hi'),
    path('contacts/', contacts, name='contacts'),
    path('add/', BbCreateView.as_view(), name='add_ad'),
    path('<slug:rubric_slug>/', by_rubric, name='by_rubric'),



]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bulletin_board.urls', namespace='bboard')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('debug/', include(debug_toolbar.urls))

]

users/urls.py
from django.urls import path
from .views import UserRegisterView, UserLoginView, UserLogoutView, UserProfileView, UserPasswordChangeView, activate

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/<slug:slug>/', UserProfileView.as_view(), name='profile'),
    path('profile/password/', UserPasswordChangeView.as_view(), name='password_change'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('activate/<str:activation_key>', activate, name='activate'),
]

bulletin_board/models.py
from django.db import models

# from django.urls import reverse
from django.utils.text import slugify

from users.models import CustomUser

from django.utils.functional import cached_property


class Rubric(models.Model):
    name = models.CharField(verbose_name='Рубрика', max_length=128, null=True)
    slug = models.SlugField(verbose_name='URL', max_length=128, unique=True)

    def __str__(self):
        return self.name

    # не пригодилось
    # def get_absolute_url(self, *args, **kwargs):
    #     return reverse('current_rubric', kwargs={'rubric_slug': self.slug})

    # нужно для того, чтобы при создании присваивался slug автоматически
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Rubric, self).save(*args, **kwargs)


class Bboard(models.Model):
    title = models.CharField(verbose_name='Товар', max_length=50)
    slug = models.SlugField(verbose_name='URL', max_length=50, unique=True)
    content = models.TextField(verbose_name='Описание', blank=True, null=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=9, decimal_places=0)
    published = models.DateTimeField(verbose_name='Опубликовано', auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(verbose_name='Обновлено', auto_now=True)

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    rubric = models.ForeignKey(Rubric, on_delete=models.PROTECT, null=True, verbose_name='Рубрика')

    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['-published']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Bboard, self).save(*args, **kwargs)

    # не пригодилось
    # def get_absolute_url(self, *args, **kwargs):
    #     return reverse('bboard:by_rubric', kwargs={'rubric_slug': self.slug})

    @cached_property
    def user_name(self):
        return self.user.username

    def username_count(self):
        lst = []
        for i in self.user_name:
            lst.append(i)
        return lst


# у меня тоже нет идей, куда его впихнуть в проекте
# пишу только ради ДЗ
class Client(models.Model):
    REGULAR = 'R'
    GOLD = 'G'
    PLATINUM = 'P'
    ANNOUNT_TYPE_CHOICE = [
        (REGULAR, 'Regular'),
        (GOLD, 'Gold'),
        (PLATINUM, 'Platinum')
    ]
    name = models.CharField(max_length=50)
    registered_on = models.DateField()
    account_type = models.CharField(
        max_length=1,
        choices=ANNOUNT_TYPE_CHOICE,
        default=REGULAR
    )

bulletin_board/forms.py
from django import forms
from .models import Rubric, Bboard



class RubricForm(forms.ModelForm):
    class Meta:
        model = Rubric
        fields = ('name',)


class BboardForm(forms.ModelForm):
    class Meta:
        model = Bboard
        fields = ('title', 'content', 'price', 'rubric')

bulletin_board/views.py
from django.conf import settings
from django.core.cache import cache
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.db.models import F, Case, Value, When

from .models import Bboard, Rubric, Client
from .forms import BboardForm
from .tasks import send_email_task

from django.views.decorators.cache import cache_page


@cache_page(120)
def bboard_index(request):
    """Главная страница со всеми рубриками"""
    bbs = Bboard.objects.all().select_related()
    rubrics = Rubric.objects.all().select_related()

    context = {
        'title': 'Главная',
        'bbs': bbs,
        'rubrics': rubrics,
    }

    return render(request, 'bulletin_board/index.html', context)


def by_rubric(request, rubric_slug):
    """Отдельно выбранная рубрика"""
    current_rubric = Rubric.objects.get(slug=rubric_slug)
    # или так, тоже работает
    # current_rubric = get_object_or_404(Rubric, slug=rubric_slug)
    bbs = Bboard.objects.filter(rubric__slug=rubric_slug).select_related()
    rubrics = Rubric.objects.all().select_related()
    context = {
        'bbs': bbs,
        'rubrics': rubrics,
        'current_rubric': current_rubric,
    }
    return render(request, 'bulletin_board/by_rubric.html', context)


def contacts(request):
    """Страница контактов"""
    context = {'title': 'Контакты'}
    return render(request, 'bulletin_board/contacts.html', context)


class BbCreateView(CreateView):
    """Страница добавления объявления с привязкой к юзеру"""
    template_name = 'bulletin_board/create.html'
    form_class = BboardForm
    success_url = reverse_lazy('bboard:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(BbCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():
            send_email_task.delay()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


def see_user_info(request):
    if settings.LOW_CACHE:
        key = 'user_info'
        user_info = cache.get(key)
        context = {
            key: user_info
        }
        if user_info is None:
            user_info = Bboard.objects.all().select_related()
            cache.set(key, user_info)
            context = {
                key: user_info
            }
    else:
        context = {
            'user_info': Bboard.objects.all().select_related()
        }
    # Берем объект с ценой 0 и меняем его на 1000
    if Bboard.objects.get(price=0):
        print(Bboard.objects.get(price=0))
        user_count = Bboard.objects.get(price=0)
        user_count.price = F('price') + 1000
        user_count.save()
    else:
        pass
    return render(request, 'bulletin_board/users_info.html', context)


def check_client_model():
    ann = Client.objects.annotate(
        discount=Case(
            When(account_type=Client.GOLD, then=Value('5%')),
            When(account_type=Client.PLATINUM, then=Value('10%'),
                 default=Value('0%'),
                 )
        )
    )
    return ann
       

bulletin_board/templates/bulletin_board/base.html
<!doctype html>
<html lang="ru">
<head>
    <!-- Обязательные метатеги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>{{ title }}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'bboard:index' %}">На главную</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bboard:contacts' %}">Контакты</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bboard:add_ad' %}">Добавить объявление</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' user.slug %}">Профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти {{ user.username }}</a>
                    </li>

                    {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/">Админка</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<br>
{% if messages %}
    {% for message in messages %}
        <div class="sticky-top">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        </div>
    {% endfor %}
{% endif %}

<br>

<div class="btn-group">
    {% for rubric in rubrics %}

        <a href="{% url 'bboard:by_rubric' rubric.slug %}" class="btn btn-primary active"
           aria-current="page">{{ rubric.name }}</a>
    {% endfor %}
</div>

{% block content %}

{% endblock %}

<!-- Вариант 1: Bootstrap в связке с Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>


</body>
</html>

bulletin_board/templates/bulletin_board/by_rubric.html
{% extends 'bulletin_board/base.html' %}
{% load static %}

{% block content %}
    <div>
        <h1>Объявления</h1>
        <h2>Рубрика: {{ current_rubric.name }}</h2>
    </div>

    {% for bb in bbs %}
        <div>
            <h2>{{ bb.title }}</h2>
            <p>Подробности: {{ bb.content }}</p>
            <p>Цена: {{ bb.price }} руб.</p>
            <p>Опубликовано: {{ bb.published|date:'d.m.Y H:i:s' }}</p>
            <p>______________</p>
        </div>
    {% endfor %}

{% endblock %}

bulletin_board/templates/bulletin_board/contacts.html
{% extends 'bulletin_board/base.html' %}
{% load static %}

{% block content %}
    <script type="text/javascript" charset="utf-8" async
            src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A6bba458d09421119526b91a269ce1478b1649da6c9b7fb4bb69c19c0f13eeb13&amp;width=500&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>
    <br>
    <p>Адрес: Россия, Санкт-Петербург, Кожевенная линия, 30</p>
    <p>Тел: +7 900 782 54 35</p>
    <p>Режим работы: Пн-Пт, с 9:00 до 18:00</p>


{% endblock %}

bulletin_board/templates/bulletin_board/create.html
{% extends 'bulletin_board/base.html' %}
{% load static %}

{% block content %}

    <h1>Добавить объявление</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
    </form>

{% endblock %}

bulletin_board/templates/bulletin_board/index.html
{% extends 'bulletin_board/base.html' %}
{% load static %}

{% block content %}

    <h1>Объявления</h1>

    {% for bb in bbs %}
        <div>
            <h2>{{ bb.title }}</h2>
            <p>Подробности: {{ bb.content }}</p>
            <p>Цена: {{ bb.price }} руб.</p>
            <p>Опубликовано: {{ bb.published|date:'d.m.Y H:i:s' }}</p>
            <p>Рубрика: <a href="{% url 'bboard:by_rubric' bb.rubric.slug %}">{{ bb.rubric.name }}</a></p>
            <p>______________</p>
        </div>
    {% endfor %}
{% endblock %}

bulletin_board/templates/bulletin_board/users_info.html
{% extends 'bulletin_board/base.html' %}
{% load static %}

{% block content %}
    {% for users in user_info %}
        {{ users.user_name }}<br>
    {% endfor %}
    {% for users in user_info %}
        {{ users.username_count }}<br>
    {% endfor %}
    {% with user_info as u %}
        its count! {{ u.count }}
    {% endwith %}
{% endblock %}